### ISSUE TITLE
script panic

### ISSUE THREAD

**Issue by FoxvibesFPV** [mvaldesshc/advanced-edgetx-dashboard#1]
not working on jumper tlite v2 elrs.
as soon as i open the telemetry page were i setup the dash script, i see error "script panic Not enogh memory"

**Comment by alexey-gamov** [comment]
> not working on jumper tlite v2 elrs.
> 
> as soon as i open the telemetry page were i setup the dash script, i see error "script panic Not enogh memory"

try the script from fork source)

**Comment by mvaldesshc** [comment]
I'll take a look at as soon as I can :)

**Comment by mvaldesshc** [comment]
Okay, just finished the end of term tests, sorry for the delay. I'll split the script into two, so that should hopefully fix this. It will take a while tho haha

**Comment by mvaldesshc** [comment]
Just realized the code for the menu was dogshit so I'm doing it again the proper way lmaooo

**Comment by mvaldesshc** [comment]
Done.
