### ISSUE TITLE
Syntax error 

### ISSUE THREAD

**Issue by Swagmiral** [mvaldesshc/advanced-edgetx-dashboard#2]
I get syntax error when opening the script, both through a telemetry screen and the file browser.
Sometimes the "mana" script works, but when I open any other of these scripts - I get a syntax error message and then the "mana" script stops working too when I try launching it again, also starts showing a syntax error.

**Comment by Roccccky** [comment]
Same here .. only mana works ... tele and set = error.

**Comment by mvaldesshc** [comment]
Only the mana script should be opened. The mana (manager script) runs the other scripts in the background (kinda). If you can't open the mana script on the telemetry page, then it is a bug.
